spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LabXpert
    username: postgres
    password: 50145014
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true
logging:
  level:
    org:
      springframework=DEBUG: DEBUG